# Generated by Django 2.1.5 on 2019-01-25 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att_path', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(max_length=12)),
                ('doc_exp_number', models.IntegerField()),
                ('doc_des', models.CharField(max_length=12)),
                ('doc_pages', models.IntegerField()),
                ('doc_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Document_identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_des', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Movements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mov_order', models.IntegerField()),
                ('id_attachments', models.IntegerField()),
                ('id_ofi_begin', models.IntegerField()),
                ('id_ofi_end', models.IntegerField()),
                ('id_doc_sender', models.IntegerField()),
                ('move_recibed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ofi_des', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_name', models.CharField(max_length=12)),
                ('per_lastname', models.CharField(max_length=12)),
                ('per_doc', models.CharField(max_length=12)),
                ('per_address', models.CharField(max_length=12)),
                ('per_cellphone', models.CharField(max_length=12)),
                ('per_type', models.CharField(max_length=12)),
                ('id_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_document_identity', to='Core.Document_identity')),
            ],
        ),
        migrations.CreateModel(
            name='Tupa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tup_des', models.CharField(max_length=12)),
                ('tup_requeriments', models.CharField(max_length=12)),
                ('tup_cost', models.CharField(max_length=12)),
                ('tup_days', models.CharField(max_length=12)),
                ('id_ofi_begin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tupa_office_begin', to='Core.Office')),
                ('id_ofi_end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tupa_office_end', to='Core.Office')),
            ],
        ),
        migrations.CreateModel(
            name='Type_document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_des', models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='id_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_person', to='Core.Person'),
        ),
        migrations.AddField(
            model_name='document',
            name='id_tupa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_tupa', to='Core.Tupa'),
        ),
        migrations.AddField(
            model_name='document',
            name='id_type_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_type_document', to='Core.Type_document'),
        ),
    ]
