# Generated by Django 2.1.5 on 2019-02-15 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att_path', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrito', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(max_length=20)),
                ('doc_exp_number', models.IntegerField(null=True)),
                ('doc_des', models.CharField(max_length=50)),
                ('doc_pages', models.IntegerField()),
                ('doc_type', models.IntegerField()),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document_identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_des', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mov_order', models.IntegerField()),
                ('id_attachments', models.IntegerField()),
                ('id_ofi_begin', models.IntegerField()),
                ('id_ofi_end', models.IntegerField()),
                ('id_doc_sender', models.IntegerField()),
                ('move_recibed', models.IntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('id_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements_document', to='Core.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ofi_des', models.CharField(max_length=40)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_name', models.CharField(max_length=20)),
                ('per_lastname', models.CharField(max_length=20)),
                ('per_doc', models.CharField(max_length=20, unique=True)),
                ('per_cellphone', models.CharField(max_length=20)),
                ('per_type', models.CharField(max_length=20)),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_departamento', to='Core.Departamento')),
                ('id_distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_distrito', to='Core.Distrito')),
                ('id_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_document_identity', to='Core.Document_identity')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=20)),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincia_departamento', to='Core.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Tupa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tup_des', models.CharField(max_length=60)),
                ('tup_requeriments', models.CharField(max_length=20)),
                ('tup_cost', models.CharField(max_length=20)),
                ('tup_days', models.CharField(max_length=20)),
                ('id_ofi_begin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tupa_office_begin', to='Core.Office')),
                ('id_ofi_end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tupa_office_end', to='Core.Office')),
            ],
        ),
        migrations.CreateModel(
            name='Type_document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_des', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='id_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_provincia', to='Core.Provincia'),
        ),
        migrations.AddField(
            model_name='document',
            name='id_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_person', to='Core.Person'),
        ),
        migrations.AddField(
            model_name='document',
            name='id_tupa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_tupa', to='Core.Tupa'),
        ),
        migrations.AddField(
            model_name='document',
            name='id_type_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_type_document', to='Core.Type_document'),
        ),
        migrations.AddField(
            model_name='distrito',
            name='id_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tupa_office_begin', to='Core.Provincia'),
        ),
        migrations.AddField(
            model_name='attachments',
            name='id_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments_document', to='Core.Document'),
        ),
    ]
