# Generated by Django 2.1.5 on 2019-02-19 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_auto_20190217_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distrito',
            name='id_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distrito_provincia', to='Core.Provincia'),
        ),
    ]
