# Generated by Django 2.1.5 on 2019-02-05 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_auto_20190203_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='id_departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='person_departamento', to='Core.Departamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='id_distrito',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='person_distrito', to='Core.Distrito'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='id_provincia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='person_provincia', to='Core.Provincia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachments',
            name='att_path',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='departamento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='distrito',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_des',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='document_identity',
            name='doc_des',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='office',
            name='ofi_des',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='per_address',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='per_cellphone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='per_doc',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='per_lastname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='per_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='per_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='provincia',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tupa',
            name='tup_cost',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tupa',
            name='tup_days',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tupa',
            name='tup_des',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tupa',
            name='tup_requeriments',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='type_document',
            name='doc_des',
            field=models.CharField(max_length=20),
        ),
    ]
