# Generated by Django 2.1.5 on 2019-02-05 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_auto_20190205_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
    ]
