# Generated by Django 2.1.5 on 2019-02-05 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_remove_person_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='per_address',
        ),
    ]
