# Generated by Django 2.1.5 on 2019-02-09 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_remove_person_per_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachments',
            name='id_doc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attachments_document', to='Core.Document'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_des',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_exp_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='ofi_des',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='person',
            name='per_doc',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='tupa',
            name='tup_des',
            field=models.CharField(max_length=60),
        ),
    ]
