# Generated by Django 2.1.5 on 2019-02-10 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_auto_20190209_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='movements',
            name='id_doc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movements_document', to='Core.Document'),
            preserve_default=False,
        ),
    ]
